### ISSUE TITLE
La asercion debe ir en el test ademas no debe ser un precio que vos elijas sino que debe ser la suma de los precios de los productos

### ISSUE THREAD

**Issue by FabrizioOtranto** [FlorMarquez1607/PushingIT-Cypress1#1]
https://github.com/FlorMarquez1607/PushingIT-Cypress1/blob/96fd2f6da2940b24a5103c0b85b716fbb53f3a9e/cypress/support/Pages/ShoppingCartPage.js#L13C1-L13C1

**Comment by FlorMarquez1607** [comment]
Buenas noches. Ya esta corregido.
